- import module

In [157]:
# @title import modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt # 개집
import seaborn
import plotly.express as px # 63빌딩
from IPython.display import Image, HTML
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors
import ast

In [158]:
movies = pd.read_csv('./datasets/tmdb.csv', index_col=0)
movies.tail()

budget                           genres  \
4798  220000  ['action', 'crime', 'thriller']   
4799    9000            ['comedy', 'romance']   
4800       0   ['comedy', 'drama', 'romance']   
4801       0                               []   
4802       0                  ['documentary']   

                                               homepage      id  \
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                            keywords original_language  \
4798  ['unitedstates–mexicobarrier', 'legs', 'arms']                es   
4799                                              []                en   
4800       ['date', 'loveatfirstsight', 'narration']                en   
4801                                              []                en   
4802             ['obsession', 'camcorder', 'crush']                en   

                 original_title  \
4798                El Mariachi   
4799                  Newlyweds   
4800  Signed, Sealed, Delivered   
4801           Shanghai Calling   
4802          My Date with Drew   

                                               overview  popularity  \
4798  El Mariachi just wants to play his guitar and ...   14.269792   
4799  A newlywed couple's honeymoon is upended by th...    0.642552   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476   
4801  When ambitious New York attorney Sam is sent t...    0.857008   
4802  Ever since the second grade when he first saw ...    1.929883   

                                   production_companies  ...    status  \
4798           [{"name": "Columbia Pictures", "id": 5}]  ...  Released   
4799                                                 []  ...  Released   
4800  [{"name": "Front Street Pictures", "id": 3958}...  ...  Released   
4801                                                 []  ...  Released   
4802  [{"name": "rusty bear entertainment", "id": 87...  ...  Released   

                                                tagline  \
4798  He didn't come looking for trouble, but troubl...   
4799  A newlywed couple's honeymoon is upended by th...   
4800                                                NaN   
4801                           A New Yorker in Shanghai   
4802                                                NaN   

                          title  vote_average vote_count  \
4798                El Mariachi           6.6        238   
4799                  Newlyweds           5.9          5   
4800  Signed, Sealed, Delivered           7.0          6   
4801           Shanghai Calling           5.7          7   
4802          My Date with Drew           6.3         16   

                         tittle  \
4798                El Mariachi   
4799                  Newlyweds   
4800  Signed, Sealed, Delivered   
4801           Shanghai Calling   
4802          My Date with Drew   

                                                   cast  \
4798  ['carlosgallardo', 'jaimedehoyos', 'petermarqu...   
4799    ['edwardburns', 'kerrybishé', 'marshadietlein']   
4800      ['ericmabius', 'kristinbooth', 'crystallowe']   
4801       ['danielhenney', 'elizacoupe', 'billpaxton']   
4802  ['drewbarrymore', 'brianherzlinger', 'coreyfel...   

                                                   crew         director  \
4798  [{'credit_id': '52fe44eec3a36847f80b280b', 'de...  robertrodriguez   
4799  [{'credit_id': '52fe487dc3a368484e0fb013', 'de...      edwardburns   
4800  [{'credit_id': '52fe4df3c3a36847f8275ecf', 'de...       scottsmith   
4801  [{'credit_id': '52fe4ad9c3a368484e16a36b', 'de...       danielhsia   
4802  [{'credit_id': '58ce021b9251415a390165d9', 'de...  brianherzlinger   

                                         

In [60]:
movies_5000 = pd.read_csv('./datasets/tmdb_5000_movies.csv')
movies_5000.tail()

budget                                             genres  \
4798  220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4799    9000  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4800       0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4801       0                                                 []   
4802       0                [{"id": 99, "name": "Documentary"}]   

                                               homepage      id  \
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language  \
4798  [{"id": 5616, "name": "united states\u2013mexi...                es   
4799                                                 []                en   
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...                en   
4801                                                 []                en   
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...                en   

                 original_title  \
4798                El Mariachi   
4799                  Newlyweds   
4800  Signed, Sealed, Delivered   
4801           Shanghai Calling   
4802          My Date with Drew   

                                               overview  popularity  \
4798  El Mariachi just wants to play his guitar and ...   14.269792   
4799  A newlywed couple's honeymoon is upended by th...    0.642552   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476   
4801  When ambitious New York attorney Sam is sent t...    0.857008   
4802  Ever since the second grade when he first saw ...    1.929883   

                                   production_companies  \
4798           [{"name": "Columbia Pictures", "id": 5}]   
4799                                                 []   
4800  [{"name": "Front Street Pictures", "id": 3958}...   
4801                                                 []   
4802  [{"name": "rusty bear entertainment", "id": 87...   

                                   production_countries release_date  revenue  \
4798  [{"iso_3166_1": "MX", "name": "Mexico"}, {"iso...   1992-09-04  2040920   
4799                                                 []   2011-12-26        0   
4800  [{"iso_3166_1": "US", "name": "United States o...   2013-10-13        0   
4801  [{"iso_3166_1": "US", "name": "United States o...   2012-05-03        0   
4802  [{"iso_3166_1": "US", "name": "United States o...   2005-08-05        0   

      runtime                               spoken_languages    status  \
4798     81.0  [{"iso_639_1": "es", "name": "Espa\u00f1ol"}]  Released   
4799     85.0                                             []  Released   
4800    120.0       [{"iso_639_1": "en", "name": "English"}]  Released   
4801     98.0       [{"iso_639_1": "en", "name": "English"}]  Released   
4802     90.0       [{"iso_639_1": "en", "name": "English"}]  Released   

                                                tagline  \
4798  He didn't come looking for trouble, but troubl...   
4799  A newlywed couple's honeymoon is upended by th...   
4800                                                NaN   
4801                           A New Yorker in Shanghai   
4802                                                NaN   

                          title  vote_average  vote_count  
4798                El Mariachi           6.6         238  
4799                  Newlyweds           5.9           5  
4800  Signed, Sealed, Delivered           7.0           6  
4801           Shanghai Calling           5.7           7  
4802          My Date with Drew           6.3          16

In [61]:
import ast
def value_import(x):
    return [i['name'] for i in ast.literal_eval(x)]
movies_5000['genres'] = movies_5000['genres'].apply(value_import)
movies_5000['keywords'] = movies_5000['keywords'].apply(value_import)

In [62]:
movies_5000['genres'][0]

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [63]:
movies_5000['keywords'][4]

['based on novel',
 'mars',
 'medallion',
 'space travel',
 'princess',
 'alien',
 'steampunk',
 'martian',
 'escape',
 'edgar rice burroughs',
 'alien race',
 'superhuman strength',
 'mars civilization',
 'sword and planet',
 '19th century',
 '3d']

In [64]:
movies_5000.head()

budget                                         genres  \
0  237000000  [Action, Adventure, Fantasy, Science Fiction]   
1  300000000                   [Adventure, Fantasy, Action]   
2  245000000                     [Action, Adventure, Crime]   
3  250000000               [Action, Crime, Drama, Thriller]   
4  260000000           [Action, Adventure, Science Fiction]   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [culture clash, future, space war, space colon...                en   
1  [ocean, drug abuse, exotic island, east india ...                en   
2  [spy, based on novel, secret agent, sequel, mi...                en   
3  [dc comics, crime fighter, terrorist, secret i...                en   
4  [based on novel, mars, medallion, space travel...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [65]:
def join_words(x):
    return (' ').join(x)

movies_5000['genres_literal'] = movies_5000['genres'].apply(join_words)

In [66]:
movies_5000['genres_literal']

0       Action Adventure Fantasy Science Fiction
1                       Adventure Fantasy Action
2                         Action Adventure Crime
3                    Action Crime Drama Thriller
4               Action Adventure Science Fiction
                          ...                   
4798                       Action Crime Thriller
4799                              Comedy Romance
4800               Comedy Drama Romance TV Movie
4801                                            
4802                                 Documentary
Name: genres_literal, Length: 4803, dtype: object

In [69]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(min_df=0.0, ngram_range=(1, 2))
genre_mat = count_vect.fit_transform(movies_5000['genres_literal'])
print(genre_mat.shape)

(4803, 276)


In [84]:
from sklearn.metrics.pairwise import cosine_similarity
genre_sim = cosine_similarity(genre_mat, genre_mat)
genre_sim[:1]

array([[1.        , 0.59628479, 0.4472136 , ..., 0.        , 0.        ,
        0.        ]])

In [83]:
# argsort() -> 유사도 높은거부터 정렬
genre_sim_sorted_ind = genre_sim.argsort()[:, ::-1]
print(genre_sim_sorted_ind[:1])

[[   0 3494  813 ... 3038 3037 2401]]


- class sklearn.neighbors.NearestNeighbors(*, n_neighbors=5, radius=1.0, algorithm='auto', leaf_size=30, metric='minkowski', p=2, metric_params=None, n_jobs=None)

In [86]:
from sklearn.neighbors import NearestNeighbors
model_knn = NearestNeighbors(n_neighbors=20, algorithm='brute', metric='cosine', n_jobs=-1)
model_knn.fit(genre_mat)

NearestNeighbors(algorithm='brute', metric='cosine', n_jobs=-1, n_neighbors=20)

In [152]:
distance, indices_result = model_knn.kneighbors(genre_mat[0], n_neighbors=20)

In [153]:
distance

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.09546597, 0.09546597, 0.1180829 , 0.1180829 ,
        0.19596975, 0.19596975, 0.19596975, 0.19596975, 0.19596975,
        0.22222222, 0.22222222, 0.22222222, 0.24407105, 0.24407105]])

In [154]:
indices_result

array([[3494,   46,    0,  813,   14,  870, 1296, 1652,  419,  420, 3208,
          72,  238, 1932, 1191,   10,  232,   61,  242, 2995]],
      dtype=int64)

In [116]:
indices = pd.Series(movies_5000.index, index=movies_5000.original_title)
indices.head(12)

original_title
Avatar                                       0
Pirates of the Caribbean: At World's End     1
Spectre                                      2
The Dark Knight Rises                        3
John Carter                                  4
Spider-Man 3                                 5
Tangled                                      6
Avengers: Age of Ultron                      7
Harry Potter and the Half-Blood Prince       8
Batman v Superman: Dawn of Justice           9
Superman Returns                            10
Quantum of Solace                           11
dtype: int64

In [133]:
def get_rocommandations(title, cosine_sim=genre_sim):
    # title = str.lower(title.replace(" ", ""))
    idx = indices[title] # 입력한 제목의 index(번호) 출력
    result = list(enumerate(cosine_sim[idx])) # (index, cosine_sim) 형태로 만듬
    result = sorted(result, key=lambda x: x[1], reverse=True) # cosine_sim을 기준으로 내림차순
    # print(result)
    result = result[1:21] # 내림차순 상위 10개
    # print(result)
    movie_indicies = [i[0] for i in result] # index(번호)를 뽑아 리스트로 만듬
    # print(book_indicies)
    return movies_5000['original_title'].iloc[movie_indicies] # 번호에 해당하는 제목을 출력

In [134]:
result = get_rocommandations('John Carter')
print(result)

7                     Avengers: Age of Ultron
31                                 Iron Man 3
47                    Star Trek Into Darkness
56                           Star Trek Beyond
59                                       2012
85        Captain America: The Winter Soldier
91               Independence Day: Resurgence
102     The Hunger Games: Mockingjay - Part 2
169        Captain America: The First Avenger
207                              Total Recall
242                            Fantastic Four
483                                  Timeline
507                          Independence Day
2433         Superman IV: The Quest for Peace
2444                          Damnation Alley
2995               Mad Max Beyond Thunderdome
3305                      The Blood of Heroes
4042                                   U.F.O.
4117                       Six-String Samurai
27                                 Battleship
Name: original_title, dtype: object


In [135]:
C = movies_5000['vote_average'].mean()
m = movies_5000['vote_count'].quantile(0.6)
def weighted_vote_average(record):
    v = record['vote_count']
    R = record['vote_average']
    return ( (v/(v+m)) * R) + ( (m/(m+v)) * C)

movies_5000['weighted_vote'] = movies_5000.apply(weighted_vote_average, axis=1)

In [136]:
movies_5000['weighted_vote']

0       7.166301
1       6.838594
2       6.284091
3       7.541095
4       6.098838
          ...   
4798    6.290894
4799    6.089611
4800    6.106650
4801    6.084894
4802    6.100782
Name: weighted_vote, Length: 4803, dtype: float64

In [138]:
def get_rocommandations_weighted_vote(title, cosine_sim=genre_sim):
    # title = str.lower(title.replace(" ", ""))
    idx = indices[title] # 입력한 제목의 index(번호) 출력
    result = list(enumerate(cosine_sim[idx])) # (index, cosine_sim) 형태로 만듬
    result = sorted(result, key=lambda x: x[1], reverse=True) # cosine_sim을 기준으로 내림차순
    # print(result)
    result = result[1:21] # 내림차순 상위 10개
    # print(result)
    movie_indicies = [i[0] for i in result] # index(번호)를 뽑아 리스트로 만듬
    # print(book_indicies)
    # movies_5000['original_title'].iloc[movie_indicies] # 번호에 해당하는 제목을 출력
    return movies_5000.iloc[movie_indicies].sort_values(by=['weighted_vote'], ascending=False)[:10]['original_title'] # 10개중 가중평점 순으로 출력

In [139]:
result = get_rocommandations_weighted_vote('John Carter')
print(result)

85        Captain America: The Winter Soldier
47                    Star Trek Into Darkness
7                     Avengers: Age of Ultron
207                              Total Recall
31                                 Iron Man 3
507                          Independence Day
169        Captain America: The First Avenger
102     The Hunger Games: Mockingjay - Part 2
56                           Star Trek Beyond
3305                      The Blood of Heroes
Name: original_title, dtype: object


In [141]:
movies = pd.read_csv('./datasets/tmdb.csv', index_col=0)
movies.tail()

budget                           genres  \
4798  220000  ['action', 'crime', 'thriller']   
4799    9000            ['comedy', 'romance']   
4800       0   ['comedy', 'drama', 'romance']   
4801       0                               []   
4802       0                  ['documentary']   

                                               homepage      id  \
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                            keywords original_language  \
4798  ['unitedstates–mexicobarrier', 'legs', 'arms']                es   
4799                                              []                en   
4800       ['date', 'loveatfirstsight', 'narration']                en   
4801                                              []                en   
4802             ['obsession', 'camcorder', 'crush']                en   

                 original_title  \
4798                El Mariachi   
4799                  Newlyweds   
4800  Signed, Sealed, Delivered   
4801           Shanghai Calling   
4802          My Date with Drew   

                                               overview  popularity  \
4798  El Mariachi just wants to play his guitar and ...   14.269792   
4799  A newlywed couple's honeymoon is upended by th...    0.642552   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476   
4801  When ambitious New York attorney Sam is sent t...    0.857008   
4802  Ever since the second grade when he first saw ...    1.929883   

                                   production_companies  ...    status  \
4798           [{"name": "Columbia Pictures", "id": 5}]  ...  Released   
4799                                                 []  ...  Released   
4800  [{"name": "Front Street Pictures", "id": 3958}...  ...  Released   
4801                                                 []  ...  Released   
4802  [{"name": "rusty bear entertainment", "id": 87...  ...  Released   

                                                tagline  \
4798  He didn't come looking for trouble, but troubl...   
4799  A newlywed couple's honeymoon is upended by th...   
4800                                                NaN   
4801                           A New Yorker in Shanghai   
4802                                                NaN   

                          title  vote_average vote_count  \
4798                El Mariachi           6.6        238   
4799                  Newlyweds           5.9          5   
4800  Signed, Sealed, Delivered           7.0          6   
4801           Shanghai Calling           5.7          7   
4802          My Date with Drew           6.3         16   

                         tittle  \
4798                El Mariachi   
4799                  Newlyweds   
4800  Signed, Sealed, Delivered   
4801           Shanghai Calling   
4802          My Date with Drew   

                                                   cast  \
4798  ['carlosgallardo', 'jaimedehoyos', 'petermarqu...   
4799    ['edwardburns', 'kerrybishé', 'marshadietlein']   
4800      ['ericmabius', 'kristinbooth', 'crystallowe']   
4801       ['danielhenney', 'elizacoupe', 'billpaxton']   
4802  ['drewbarrymore', 'brianherzlinger', 'coreyfel...   

                                                   crew         director  \
4798  [{'credit_id': '52fe44eec3a36847f80b280b', 'de...  robertrodriguez   
4799  [{'credit_id': '52fe487dc3a368484e0fb013', 'de...      edwardburns   
4800  [{'credit_id': '52fe4df3c3a36847f8275ecf', 'de...       scottsmith   
4801  [{'credit_id': '52fe4ad9c3a368484e16a36b', 'de...       danielhsia   
4802  [{'credit_id': '58ce021b9251415a390165d9', 'de...  brianherzlinger   

                                         

In [142]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'tittle', 'cast', 'crew', 'director', 'soup'],
      dtype='object')

In [159]:
def join_words(x):
    return ('').join(x)

movies['soup'] = movies['soup'].apply(join_words)

In [160]:
movies['soup']

0       cultureclash future spacewar samworthington zo...
1       ocean drugabuse exoticisland johnnydepp orland...
2       spy basedonnovel secretagent danielcraig chris...
3       dccomics crimefighter terrorist christianbale ...
4       basedonnovel mars medallion taylorkitsch lynnc...
                              ...                        
4798    unitedstates–mexicobarrier legs arms carlosgal...
4799     edwardburns kerrybishé marshadietlein edwardb...
4800    date loveatfirstsight narration ericmabius kri...
4801       danielhenney elizacoupe billpaxton danielhsia 
4802    obsession camcorder crush drewbarrymore brianh...
Name: soup, Length: 4803, dtype: object

In [161]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(min_df=0.0, ngram_range=(1, 2))
soup_mat = count_vect.fit_transform(movies['soup'])
print(soup_mat.shape)

(4803, 41315)


In [162]:
from sklearn.neighbors import NearestNeighbors
model_knn = NearestNeighbors(n_neighbors=20, algorithm='auto', metric='cosine', n_jobs=-1)
model_knn.fit(soup_mat)

NearestNeighbors(metric='cosine', n_jobs=-1, n_neighbors=20)

In [166]:
distances, indices_result = model_knn.kneighbors(soup_mat[2], n_neighbors=11)

In [167]:
indices_result

array([[   2,   29, 1084, 2156,   11, 1615, 1082, 1234,  356,   72, 1073]],
      dtype=int64)

In [168]:
distance

array([[6.66133815e-16, 5.78947368e-01, 6.84210526e-01, 6.84210526e-01,
        7.36842105e-01, 7.36842105e-01, 7.36842105e-01, 7.36842105e-01,
        7.36842105e-01, 7.36842105e-01, 7.36842105e-01]])

In [ ]:
indices = pd.Series(movies.index, index=movies.original_title)
indices.head(12)

In [184]:
model_knn.kneighbors(soup_mat[indices['John Carter']])

(array([[6.66133815e-16, 6.81857619e-01, 6.84210526e-01, 7.03825561e-01,
         7.12981076e-01, 7.21792558e-01, 7.36842105e-01, 7.36842105e-01,
         7.36842105e-01, 7.36842105e-01, 7.36842105e-01, 7.36842105e-01,
         7.36842105e-01, 7.36842105e-01, 7.36842105e-01, 7.36842105e-01,
         7.36842105e-01, 7.36842105e-01, 7.36842105e-01, 7.36842105e-01]]),
 array([[   4,   83,  270, 4117, 2444,   91,   56,  507, 1001,    7,   59,
         2995, 1083,  212,  976,  260,   31,   47,   28, 2815]],
       dtype=int64))

In [195]:
def get_rocommandations(title, model=model_knn):
    # title = str.lower(title.replace(" ", ""))
    idx = indices[title] # 입력한 제목의 index(번호) 출력
    distances, indices_result = model_knn.kneighbors(soup_mat[idx], n_neighbors=11) # (1 - cosine_sim, index) 형태
    result = indices_result[0][1:] # 자신을 제외한 
    similiarity = list(1 - np.array(distances))[0]
    return (movies['original_title'].iloc[result], similiarity)

In [196]:
get_rocommandations('Total Recall')

(83                        The Lovers
 4117              Six-String Samurai
 91      Independence Day: Resurgence
 56                  Star Trek Beyond
 507                 Independence Day
 1083                    Babylon A.D.
 28                    Jurassic World
 31                        Iron Man 3
 2995      Mad Max Beyond Thunderdome
 976                 Escape from L.A.
 Name: original_title, dtype: object,
 array([1.        , 0.31814238, 0.29617444, 0.27820744, 0.26315789,
        0.26315789, 0.26315789, 0.26315789, 0.26315789, 0.26315789,
        0.26315789]))

In [197]:
get_rocommandations('John Carter')[1]

array([1.        , 0.31814238, 0.31578947, 0.29617444, 0.28701892,
       0.27820744, 0.26315789, 0.26315789, 0.26315789, 0.26315789,
       0.26315789])

In [207]:
title_series, sim = get_rocommandations('John Carter')
for i in range(len(title_series)):
    print(f'{i+1}번째 추천 영화는 \n')
    print(f'영화 {list(title_series)[i]}이고 유사도는 {sim[i] * 100:.0f}%입니다')
    print(f'=============\n')

1번째 추천 영화는 

영화 The Lovers이고 유사도는 100%입니다

2번째 추천 영화는 

영화 The Martian이고 유사도는 32%입니다

3번째 추천 영화는 

영화 Six-String Samurai이고 유사도는 32%입니다

4번째 추천 영화는 

영화 Damnation Alley이고 유사도는 30%입니다

5번째 추천 영화는 

영화 Independence Day: Resurgence이고 유사도는 29%입니다

6번째 추천 영화는 

영화 Mad Max Beyond Thunderdome이고 유사도는 28%입니다

7번째 추천 영화는 

영화 The Day After Tomorrow이고 유사도는 26%입니다

8번째 추천 영화는 

영화 Babylon A.D.이고 유사도는 26%입니다

9번째 추천 영화는 

영화 Jurassic World이고 유사도는 26%입니다

10번째 추천 영화는 

영화 2012이고 유사도는 26%입니다



#### Item Based Collaborative Filtering

In [228]:
rating_data = pd.read_csv('./datasets/ratings_small.csv')
movie_data = pd.read_csv('./datasets/movies_small.csv')

In [229]:
rating_data.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [230]:
movie_data.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [231]:
rating_data.drop('timestamp', axis=1, inplace=True)
rating_data.head()

userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [232]:
user_movie_rating_df = pd.merge(rating_data, movie_data, on='movieId')

In [233]:
movie_user_rating = user_movie_rating_df.pivot_table('rating', index=['title'], columns=['userId'])
user_movie_rating = user_movie_rating_df.pivot_table('rating', index=['userId'], columns=['title'])

In [234]:
movie_user_rating.fillna(0, inplace=True)

In [237]:
from scipy.sparse import csr_matrix
movie_user_rating_mat = csr_matrix(movie_user_rating.values)

In [238]:
from sklearn.neighbors import NearestNeighbors
model_knn = NearestNeighbors(n_neighbors=20, algorithm='auto', metric='cosine', n_jobs=-1)
model_knn.fit(movie_user_rating_mat)

NearestNeighbors(metric='cosine', n_jobs=-1, n_neighbors=20)

In [239]:
distances, indices_result = model_knn.kneighbors(movie_user_rating_mat[0], n_neighbors=11)

In [240]:
indices_result

array([[8806, 4425, 2398, 2397, 8807, 8860, 3449, 7188, 5111, 3448, 1015]],
      dtype=int64)

In [241]:
movie_data['title'][8806]

'Home (2015)'