tf.keras.preprocessing.text.text_to_word_sequence(
    input_text,
    filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
    lower=True,
    split=' '
)

In [15]:
import numpy as np
import tensorflow as tf
from numpy import array

from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.preprocessing.text import Tokenizer, text_to_word_sequence

text = "해보지 않으면 해낼 수 없다"

result = text_to_word_sequence(text)
print('\n원문:\n', text)
print('\n토큰화:\n', result)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


In [7]:
docs = ['먼저 텍스트의 각 단어를 나누어 텍스트의 단위를 토큰화 합니다.',
        '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.',
        '토큰화 한 결과는 딥러닝에서 사용 할 수 있습니다.']
token = Tokenizer() # 토큰화 함수 지정
token.fit_on_texts(docs) # 토큰화 함수에 문장 적용
# 단어의 빈도수를 계산한 결과를 각 옵션에 맞추어 출력합니다.
print("\n단어 카운트:\n", token.word_counts)
# Tokenizer()의 word_counts 함수는 순서를 기억하는 OrderedDict클래스를 사용합니다.

# 출력되는 순서는 랜덤입니다.
print("\n문장 카운트:\n", token.document_count)
print("\n각 단어가 몇개의 문장에 포함되어 있는가:\n", token.word_docs)
print("\n각 단어에 매겨진 인덱스 값:\n", token.word_index)


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 3), ('각', 1), ('단어를', 1), ('나누어', 1), ('단위를', 1), ('토큰화', 3), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용', 1), ('할', 1), ('수', 1), ('있습니다', 1)])

문장 카운트:
 3

각 단어가 몇개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'각': 1, '토큰화': 3, '먼저': 1, '단어를': 1, '나누어': 1, '합니다': 1, '텍스트의': 2, '단위를': 1, '단어로': 1, '딥러닝에서': 2, '해야': 1, '인식됩니다': 1, '할': 1, '사용': 1, '있습니다': 1, '결과는': 1, '수': 1, '한': 1})

각 단어에 매겨진 인덱스 값:
 {'텍스트의': 1, '토큰화': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '단위를': 8, '합니다': 9, '단어로': 10, '해야': 11, '인식됩니다': 12, '한': 13, '결과는': 14, '사용': 15, '할': 16, '수': 17, '있습니다': 18}


- tf.keras.preprocessing.text.Tokenizer(
    num_words=None,
    filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
    lower=True,
    split=' ',
    char_level=False,
    oov_token=None,
    analyzer=None,
    **kwargs
)

In [9]:
text = "오랫동안 꿈꾸는 자는 그 꿈을 닮아간다"

token = Tokenizer()
token.fit_on_texts([text])
print('문장의 토큰화:', token.word_index)

x = token.texts_to_sequences([text])
print('문장의 숫자화:', x)

from tensorflow.keras.utils import to_categorical

word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes=word_size)
print('문장의 원-핫 인코딩:\n', x)

문장의 토큰화: {'오랫동안': 1, '꿈꾸는': 2, '자는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}
문장의 숫자화: [[1, 2, 3, 4, 5, 6]]
문장의 원-핫 인코딩:
 [[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


tf.keras.utils.pad_sequences(
    sequences,
    maxlen=None,
    dtype='int32',
    padding='pre',
    truncating='pre',
    value=0.0
)

In [55]:
docs = ['너무 재밌네요',
        '최고예요',
        '참 잘 만든 영화예요',
        '추천하고 싶은 영화입니다.',
        '한 번 더 보고싶네요',
        '글쎄요',
        '별로예요',
        '생각보다 지루하네요',
        '연기가 어색해요',
        '재미없어요']
class_ = array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)
x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n",x)
padded_x = pad_sequences(x, 4)
print("\n패딩 결과:", padded_x)

print("\n딥러닝 모델 시작:")

word_size = len(token.word_index) + 1

model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])
model.fit(padded_x, class_, epochs=22)
print(f"\n Accuracy: {model.evaluate(padded_x, class_)[1]:.4f}")

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고싶네요': 14, '글쎄요': 15, '별로예요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}

리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13, 14], [15], [16], [17, 18], [19, 20], [21]]

패딩 결과: [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]

딥러닝 모델 시작:
Epoch 1/22
1/1 [==============================] - 1s 1s/step - loss: 0.6855 - accuracy: 0.9000
Epoch 2/22
1/1 [==============================] - 0s 14ms/step - loss: 0.6836 - accuracy: 0.9000
Epoch 3/22
1/1 [==============================] - 0s 11ms/step - loss: 0.6817 - accuracy: 1.0000
Epoch 4/22
1/1 [==============================] - 0s 11ms/step - loss: 0.6798 - accuracy: 1.0000
Epoch 5/22
1/1 [==============================] - 0s 23ms/step - loss: 0.6778 - accuracy: 1.0000
Epoch 6

In [56]:
word = ['생각보다 재밌네요']
x_test = token.texts_to_sequences(word)
print(x_test)

[[17, 2]]


In [57]:
padded_x_test = pad_sequences(x_test, 4)
print("\n패딩 결과:", padded_x_test)


패딩 결과: [[ 0  0 17  2]]


In [58]:
model.predict(padded_x_test)

1/1 [==============================] - 0s 62ms/step


array([[0.49428397]], dtype=float32)